SPOT-125 UI Ingest summary link bug fixed
daortizh/incubator-spot pull request #17
Opened 2017-03-08 23:22 UTC by bryanmontesv

Added the necessary element to show Ingest summary link on ui/ingest-sumary.html

2017-03-08 23:27 UTC, daortizh commented
Ingest summary link is missing start date. We need start date and end date to make sure we are linking to the same page and hopefully prevent a page load

2017-03-08 23:28 UTC, daortizh requested changes
Ingest summary link is missing start date. We need start date and end date to make sure we are linking to the same page and hopefully prevent a page load

2017-03-09 00:25 UTC, bryanmontesv commented
Changes done!

2017-03-09 15:07 UTC, daortizh approved these changes

2017-03-09 15:08 UTC, merged